#!/bin/bash

#SBATCH --ntasks=256
#SBATCH --nodes=4
#SBATCH --partition=ngcm_amd
#SBATCH --job-name=6k
#SBATCH --time=30:00:00
#SBATCH --output=JOB.out
# SBATCH --exclude=ruby035,ruby036,ruby037
# SBATCH --dependency=afterok:1908224

echo "Starting calculation at $(date)"
echo "---------------------------------------------------------------"

module purge
module load conda
source activate an
module load gcc openmpi/4.1.4/gcc

python run-val.py

