#!/bin/bash

#SBATCH --ntasks=128
#SBATCH --nodes=2
#SBATCH --partition=amd
#SBATCH --job-name=k_test
#SBATCH --time=09:00:00

echo "Starting calculation at $(date)"
echo "---------------------------------------------------------------"

module purge
module load conda
source activate an
module load gcc openmpi/4.1.4/gcc

python3 run-ct-st.py
