#!/bin/bash

#SBATCH --ntasks=64
#SBATCH --nodes=1
#SBATCH --partition=amd
#SBATCH --job-name=kin_test
#SBATCH --time=04:00:00

echo "Starting calculation at $(date)"
echo "---------------------------------------------------------------"

module purge
module load conda
source activate an
module load gcc openmpi/4.1.4/gcc

python run-ct-st.py
